### ISSUE TITLE
Error: https fetch: Get https://dmitri.shuralyov.com/app/changes?go-get=1: dial tcp 172.93.50.41:443: connect: no route to host

### ISSUE THREAD

**Issue by wallrj** [shurcooL/home#25]
Same as https://github.com/shurcooL/home/issues/23, I'm getting build errors when we attempt to download packages from your site:

```
go: dmitri.shuralyov.com/app/changes@v0.0.0-20180602232624-0a106ad413e3: unrecognized import path "dmitri.shuralyov.com/app/changes" (https fetch: Get https://dmitri.shuralyov.com/app/changes?go-get=1: dial tcp 172.93.50.41:443: connect: no route to host)
```

```
curl -v https://dmitri.shuralyov.com
* Rebuilt URL to: https://dmitri.shuralyov.com/
*   Trying 172.93.50.41...
* TCP_NODELAY set
* connect to 172.93.50.41 port 443 failed: No route to host
* Failed to connect to dmitri.shuralyov.com port 443: No route to host
* Closing connection 0
curl: (7) Failed to connect to dmitri.shuralyov.com port 443: No route to host

```

**Comment by dmitshur** [comment]
Hi, thanks for reporting.

It seems my server provider was having some networking issues that prevented the server from being reachable.

The issue appears to be resolved as of about 15 minutes ago. Let me know if you're seeing otherwise.

**Comment by dmitshur** [comment]
My server provider confirmed there was a network problem with their upstream. It has been resolved by now.

Here's a graph of ?go-get=1 requests my server was responding to successfully to provide visibility on the problem:

![image](https://user-images.githubusercontent.com/1924134/57956134-f244db00-78c5-11e9-878f-88f1c866d6a2.png)

(The times are EDT.)

Sorry for the trouble.
