### ISSUE TITLE
intermittent "dial tcp: i/o timeout" errors doing GET /html/belt?go-get=1

### ISSUE THREAD

**Issue by wallrj** [shurcooL/home#28]
This error occurred on our Gitlab CI system with jobs running on Google Cloud.

```
go: dmitri.shuralyov.com/html/belt@v0.0.0-20180602232347-f7d459c86be0: unrecognized import path "dmitri.shuralyov.com/html/belt" (https fetch: Get https://dmitri.shuralyov.com/html/belt?go-get=1: dial tcp 172.93.50.41:443: i/o timeout)
go: error loading module requirements
```

It's happened before in #25 and #23 

It seems to be an intermittent failure and I can't reproduce it using curl from my own network.

```
curl -v 'https://dmitri.shuralyov.com/html/belt?go-get=1'

<meta name="go-import" content="dmitri.shuralyov.com/html/belt git https://dmitri.shuralyov.com/html/belt">
<meta name="go-import" content="dmitri.shuralyov.com/html/belt mod https://dmitri.shuralyov.com/api/module">
* Connection #0 to host dmitri.shuralyov.com left intact
<meta name="go-source" content="dmitri.shuralyov.com/html/belt https://dmitri.shuralyov.com/html/belt https://gotools.org/dmitri.shuralyov.com/html/belt https://gotools.org/dmitri.shuralyov.com/html/belt#{file}-L{line}">
```

**Comment by dmitshur** [comment]
Thanks for reporting.

It's not a problem at this time.

Given it's intermittent, I suspect it might be related to deploys of my personal website. They're quick, but not instantaneous, so there might be a few seconds of downtime a few times each week. I haven't implemented zero-downtime deploys.

Have you considered using the Go module mirror (see https://proxy.golang.org for more information about it) for increased reliability? /cc @katiehockman

**Comment by wallrj** [comment]
Thanks, we haven't encountered this issue since. Will try using proxy.golang.org, as suggested.
