### ISSUE TITLE
Error: https fetch: Get https://dmitri.shuralyov.com/app/changes?go-get=1: dial tcp 172.93.50.41:443: i/o timeout

### ISSUE THREAD

**Issue by evanger24** [shurcooL/home#29]
Similar to #23 and #25, build errors when trying to download packages from your site.

`go: dmitri.shuralyov.com/app/changes@v0.0.0-20180602232624-0a106ad413e3: unrecognized import path "dmitri.shuralyov.com/app/changes" (https fetch: Get https://dmitri.shuralyov.com/app/changes?go-get=1: dial tcp 172.93.50.41:443: i/o timeout)`

`curl -v https://dmitri.shuralyov.com
* About to connect() to dmitri.shuralyov.com port 443
*   Trying 172.93.50.41... Connection timed out
* couldn't connect to host
* Closing connection #0
curl: (7) couldn't connect to host`

**Comment by dmitshur** [comment]
Thanks for reporting.

I'm not able to reproduce it from my current location:

```
$ curl -is https://dmitri.shuralyov.com 2>&1 | head -n 5
HTTP/2 200 
content-type: text/html; charset=utf-8
date: Wed, 04 Sep 2019 23:03:08 GMT

<html>
```

Is it reproducible for you right now? What part of the world are you making the HTTP request from? It might be a networking issue that affects only some IPs/locations.

**Comment by dmitshur** [comment]
I tried a global latency testing tool at [latency.apex.sh](https://latency.apex.sh), and it's not finding availability problems from any of the locations it tests from:

https://latency.apex.sh/?url=https%3A%2F%2Fdmitri.shuralyov.com%2Fapp%2Fchanges%3Fgo-get%3D1

![image](https://user-images.githubusercontent.com/1924134/64299604-c23e4800-cf47-11e9-919b-fce85d6ce41b.png)

If you can provide more information, it'd be helpful in trying to diagnose this issue. Thanks.

**Comment by evanger24** [comment]
Thank you so much for your quick response. I encountered a firewall on my end. Thank you again for looking into this.
