### ISSUE TITLE
h-card.photo[0] type is map[string]string, want string

### ISSUE THREAD

**Issue by toby3d** [shurcooL/home#45]
I've encountered a strange bug due to which I can't authenticate to your site:

![](https://github.com/shurcooL/home/assets/5412322/23a164f7-44ff-4e36-8ea2-fde395e21c6a)

Previously my authentication attempts were successful when I used [indielogin.com](https://indielogin.com/) server, I even leave some reactions on your publications. But recently I am using [my own server](https://auth.toby3d.me/) ([source](https://source.toby3d.me/toby3d/auth)). *Maybe* the problem is related to this, but I'm not sure.

The [Golang microformats2 parser](https://go.microformats.io/) shows that my photo is a `string` in an `slice`, so I don't really see how a `map` could be involved, unless you are using a your own parser that interprets the data in a different way:

```json
{
  "items": [
    ...
    {
      "type": [
        "h-card"
      ],
      "properties": {
        "email": [
          "mailto:toby3d@toby3d.me"
        ],
        "family-name": [
          "Lebedev"
        ],
        "given-name": [
          "Maxim"
        ],
        "name": [
          "Maxim Lebedev"
        ],
        "nickname": [
          "toby3d"
        ],
        "note": [
          "Creative dude from Russia. Altruist, programmer and supporter of IndieWeb. I'm into music, video games and anime."
        ],
        "photo": [
          "https://toby3d.me/photo.jpg"
        ],
        "url": [
          "https://toby3d.me/"
        ]
      }
    }
  ],
  "rels": {
    ...
  },
  "rel-urls": {
    ...
  }
}
```

**Comment by dmitshur** [comment]
Thanks very much for reporting this.

I'm able to reproduce the error locally with:

```Go
doc, err := html.Parse(strings.NewReader(`<div class="[ h-card ][ sidebar ]"><img class="u-photo" src="https://example.com/photo.jpg" alt="Example"></div>`))
if err != nil {
	log.Fatalln(err)
}
data := microformats.ParseNode(doc, &url.URL{})
photo, err := photoURL(data)
if err != nil {
	fmt.Println(err)
	return
}
fmt.Println(photo)

// Output:
// h-card.photo[0] type is map[string]string (value is []interface {}{map[string]string{"alt":"Example", "value":"https://example.com/photo.jpg"}}), want string
```

_([playground link](https://go.dev/play/p/nvsUTkSuYqm))_

I'll need to read up a bit more on the h-card spec, but it looks like `photoURL` isn't taking into account that the type won't be a `string` when the image has an "alt" property:

https://github.com/willnorris/microformats/blob/07cd52d5def16f9e5f227c803c208fb62a80523f/microformats.go#L317-L324

I've deployed a change to handle that case, so you should be able to try to login again and see if it works. I'll leave the issue open to follow up more thoroughly.

**Comment by toby3d** [comment]
> I've deployed a change to handle that case, so you should be able to try to login again and see if it works. I'll leave the issue open to follow up more thoroughly.

Yeah, now it works perfectly:

![](https://github.com/shurcooL/home/assets/5412322/63194070-1fb0-4b18-808b-23960567df14)
